### PR TITLE
Publish to bintray

### PR DESCRIPTION
**Pull request by Duhemm**
~~I've merged the two previous subprojects (previously library and plugin) into only one project.~~

~~I've added the plugin and configuration to publish it to Bintray directly in `sbt/sbt-plugin-releases` repository.~~

~~**I've published this as v0.0.1 on Bintray.** Hope that's okay.~~

I've added a license (BSD 3 clauses, the same as sbt/sbt I think).
Both the plugin and the library are configured to be published in `sbt/sbt-plugin-release`

### CODE REVIEW

**Comment by eed3si9n** [comment]
I don't think it's a good idea to merge the two subprojects in case we want to use datatype portion beyond this plugin.

**Comment by Duhemm** [comment]
Where should the library used by the plugin be published then? In sbt/maven-releases?

**Comment by eed3si9n** [comment]
sbt-plugin-releases is ok for now.

**Comment by Duhemm** [comment]
I've made the changes. Both the plugin and the library are ready to be published in `sbt/sbt-plugin-releases`.

**Comment by eed3si9n** [comment]
I think we should use Apache-2.0 regardless of what sbt currently is using.

**Comment by Duhemm** [comment]
Done

**Comment by eed3si9n** [comment]
Could you squash the whole thing into a single commit, plz?

**Comment by Duhemm** [comment]
It's done

**Pull request merged**
